apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: hello-app
  name: hello-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: hello-app
  template:
    metadata:
      labels:
        run: hello-app
    spec:
      containers:
      - image: gcr.io/project-kubernetes-242705/welcome
        name: hello-app
        ports:
        - containerPort: 8080
